[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[services]]
name = "rag-system"
type = "web"

[services.rag-system]
port = 3001

[[services.rag-system.envs]]
PINECONE_API_KEY = "$PINECONE_API_KEY"
PINECONE_INDEX_NAME = "syncwithme-travel-rag"
OPENAI_API_KEY = "$OPENAI_API_KEY"
NODE_ENV = "production"
PORT = "3001"